[package]
name = "chat-history-manager-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
simd-json = "0.10.3"
mimalloc = "0.1.37" # As advise by SIMD Json docs
chrono = "0.4.26"
regex = "1.8.4"
lazy_static = "1.4.0"

# Protobuf and web service
protobuf = "3.2.0"
tonic = "0.9.2"
tonic-reflection = "0.9.2"
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
prost = "0.11.9"
unicode-segmentation = "1.10.1"

[dependencies.uuid]
version = "1.3.3"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[build-dependencies]
tonic-build = "0.9.2"
