[package]
name = "chat-history-manager-rust"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
itertools = "0.11.0"
simd-json = "0.10.7"
mimalloc = "0.1.39" # As advise by SIMD Json docs
chrono = "0.4.31"
regex = "1.9.6"
lazy_static = "1.4.0"
hashers = "1.0.1"
rand = "0.8.5"
derive_deref = "1.1.1"
error-chain = "0.12.4"
ical = "0.8.0"

# Database
rusqlite = { version = "0.29.0", features = ["bundled"] }

# Protobuf and web service
protobuf = "3.3.0"
tonic = "0.10.2"
tonic-reflection = "0.10.2"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
prost = "0.12.1"
unicode-segmentation = "1.10.1"
deepsize = "0.2.0"

# Logging
log = "0.4.20"
env_logger = "0.10.0"

[dependencies.uuid]
version = "1.4.1"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[dev-dependencies]
pretty_assertions = "1.4.0"

[build-dependencies]
tonic-build = "0.10.2"
